xpos334/xpos334/Controllers/ProductController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using System.Net;
using xpos334.datamodels;
using xpos334.Services;
using xpos334.viewmodels;
using Xpos334.Services;

namespace xpos334.Controllers
{
    public class ProductController : Controller
    {
        private CategoryService categoryService;
        private VariantService variantService;
        private ProductService productService;
        private readonly IWebHostEnvironment webHostEnvirontment;
        private int IdUser = 1;

        public ProductController(CategoryService  _categoryService, VariantService  _variantService, ProductService  _productService, IWebHostEnvironment _webHostEnvironment)
        {
            categoryService = _categoryService;
            variantService = _variantService;
            productService = _productService;
            webHostEnvirontment = _webHostEnvironment;
        }
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";
            ViewBag.PriceSort = sortOrder == "price" ? "price_desc" : "price";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            List<VMTblProduct> data = await productService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameVariant.ToLower().Contains(searchString.ToLower())
                    || a.NameCategory.ToLower().Contains(searchString.ToLower())
                     || a.NameProduct.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameProduct).ToList();
                    break;
                case "price_desc":
                    data = data.OrderByDescending(a => a.Price).ToList();
                    break;
                case "price":
                    data = data.OrderBy(a => a.Price).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameProduct).ToList();
                    break;
            }

            return View(PaginatedList<VMTblProduct>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
          
        }
        public async Task<IActionResult> Create()
        {
            VMTblProduct data = new VMTblProduct();

            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;

            List<VMTblVariant> listVariant = await variantService.GetAllData();
            ViewBag.ListVariant = listVariant;
            return PartialView(data);
        }
        public async Task<JsonResult> GetDataByIdCategory(int id)
        {
            List<VMTblVariant> data = await variantService.GetDataByIdCategory(id);
            return Json(data);
        }
        public async Task<JsonResult> CheckNameIsExist(string name, int id, int idVariant)
        {
            bool isExist = await productService.CheckByName(name, id, idVariant);
            return Json(isExist);
        }
        [HttpPost]
        public async Task<IActionResult> Create(VMTblProduct dataParam)
        {
            if(dataParam.ImageFile != null) 
            {
                dataParam.Image = Upload(dataParam.ImageFile);
            }
            //dataParam.CreateBy = IdUser;
            VMResponse respon = await productService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public string Upload(IFormFile ImageFile) 
        {
            string uniqueFileName = "";

            if(ImageFile != null)
            {
                string uploadFolder = Path.Combine(webHostEnvirontment.WebRootPath, "images");
                uniqueFileName = Guid.NewGuid().ToString() + "_"+ ImageFile.FileName;
                string filePath = Path.Combine(uploadFolder, uniqueFileName);
                using(var fileStream = new FileStream(filePath, FileMode.Create))
                {
                    ImageFile.CopyTo(fileStream);
                }
            }
            return uniqueFileName;
        }
        public async Task<IActionResult> Edit(int id)
        {
            VMTblProduct data = await productService.GetDataById(id);

            List<TblCategory> listCategory = await categoryService.GetAllData();
            ViewBag.ListCategory = listCategory;

            List<VMTblVariant> listVariant = await variantService.GetDataByIdCategory(id);
            ViewBag.ListVariant = listVariant;

            return PartialView(data);

        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMTblProduct dataParam)
        {
            if (dataParam.ImageFile != null)
            {
                dataParam.Image = Upload(dataParam.ImageFile);
            }
            //dataParam.CreateBy = IdUser;
            VMResponse respon = await productService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }
        public async Task<IActionResult> Detail(int id)
        {
            VMTblProduct data = await productService.GetDataById(id);
            return PartialView(data);
        }

        public async Task<IActionResult> Delete(int id)
        {
            VMTblProduct data = await productService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            VMResponse respon = await productService.Delete(id);
            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return RedirectToAction("Index");
        }


    }
}

xpos334/xpos334/Views/Product/Create.cshtml
@using xpos334.viewmodels;
@model VMTblProduct

@{
    Layout = null;
    ViewData["Title"] = "Create Product";
}

<div class="card">
    <div class="card-body">
        @* <div class="h4 mb-4">@ViewData["Title"]</div> *@
        <div class="card-title">@ViewData["Title"]</div>

        <form asp-action="Create" method="post" id="form_input" enctype="multipart/form-data">
            <div class="mb-4 row">
                <label for="NameProduct" class="col-sm-4 col-form-label">Name Product</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameProduct" name="NameProduct" value="@Model.NameProduct">
                    <span id="validate_NameProduct" class="text-danger"></span>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdCategory",
                    new SelectList(ViewBag.ListCategory, "Id", "NameCategory"),
                    "--Pilih Category--",
                    new {@class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdVariant" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdVariant",
                    new SelectList(ViewBag.ListVariant, "Id", "NameVariant"),
                    "--Pilih Variant--",
                    new {@class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Price" class="col-sm-4 col-form-label">Price</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Price" name="Price" value="@Model.Price">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Stock" class="col-sm-4 col-form-label">Stock</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Stock" name="Stock" value="@Model.Stock">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="ImageFile" class="col-sm-4 col-form-label">Upload Image</label>
                <div class="col-sm-8">
                    <input type="file" class="form-control" id="ImageFile" name="ImageFile" value="@Model.Image">
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="Product" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            NameProduct: {
                required: true,
                minlength: 3,
            },
            Price: {
                required: true,
                number: true,
            },
            Stock: {
                required: true,
                number: true,
            },
            IdCategory: "required",
            IdVariant: "required",
            ImageFile: {
                required: true,
                typeFile: "jpg|jpeg|png",
                sizeFile: true,
            },
        },
        messages: {
            NameProduct: {
                required: "Please fill Name Product",
                minlength: "The name must consist of at least 3 character"
            },
            Price: {
                required: "Please fill price",
                number: "Please fill number only",
            },
            Stock: {
                required: "Please fill stock",
                number: "Please fill number only",
            },
            IdCategory: "Please select category",
            IdVariant: "Please select category",
            ImageFile: {
                required: "Please fill image",
                typeFile: "Please upload jpn|jpeg|png",
                sizeFile: "Please upload file max size 1 mb",
            },
        },
        submitHandler: function (form) {
            var name = $("#NameProduct").val()
            var id = 0
            var idVariant = $("#IdVariant").val()

            $.ajax({
                url: "/Product/CheckNameIsExist",
                type: "get", //type atau method sama aja.
                data: { name: name, id: id, idVariant: idVariant },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_NameProduct").text("Name Product is Already Exists");
                        return true;
                    }
                    else {
                        fungsiSubmit(form)
                    }
                }

            })
        }
    })

    function fungsiSubmit(form) {
        var formData = new FormData()
        var dataForm = $(form).serializeArray()
        $.each(dataForm, function (key, input) {
            formData.append(input.name, input.value)
        })
        var file =$("#ImageFile").prop("files")
        if (file.length > 0) {
            formData.append("ImageFile", file[0])
        }
        $.ajax({
            url: "/Product/Create",
            type: "post",
            data: formData,
            dataType: "json",
            contentType: false,
            processData: false,
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {
                    $("#my_Modal").modal("hide")

                    // toastr.success(
                    //     data.message,
                    //     '',
                    //     {
                    //         timeOut: 500,
                    //         fadeOut: 500,
                    //         onHidden: function () {
                    //             window.location.reload()
                    //         }
                    //     }
                    // )
                    Swal.fire({
                        title: data.message,
                        width: 600,
                        padding: "3em",
                        color: "#2b1d8a",
                        background: "#fff url(/adminmart/assets/images/background/img5.png)",
                        backdrop: `
                                    rgba(0,0,123,0.4)
                                        url("/images/bgr.gif")
                                    left top
                                    no-repeat
                                  `,
                      //  text: data.message
                    }).then((result) => {
                        // Jika pengguna menekan tombol OK, result.value akan berisi true
                        if (result.value) {
                            // Reload halaman setelah menekan tombol OK
                            window.location.reload();
                        }
                    });

                }
                else {
                    Swal.fire({
                        icon : 'error',
                        title: 'warning!',
                        text: data.message
                    })
                }

            }
        })
    }
    jQuery.validator.addMethod("typeFile", function (value, element, param) {
        return value.match(new RegExp("." + param + "$"));
    });
    jQuery.validator.addMethod("sizeFile", function (val, element) {
        var size = element.files[0].size;
        if (size > 1048576)// checks the file more than 1 MB
        {
            return false;
        } else {
            return true;
        }
    });

    $("#IdCategory").change(function () {
        var idCategory = $(this).val()
        $.ajax({
            url: "/Product/GetDataByIdCategory",
            data: { id: idCategory },
            type: "get",
            dataType: "Json",
            success: function (respon) {
                $("#IdVariant").empty()
                $("#IdVariant").append("<option value=''>--PilihVariant--</option>")
                $.each(respon, function (index, res) { //untuk perulangan
                    $("#IdVariant").append("<option value='" + res.id + "'>" + res.nameVariant + "</option>")
                })
            }
        })
    })
</script>

xpos334/xpos334/Views/Product/Delete.cshtml
@using xpos334.viewmodels;
@model VMTblProduct
@{
    ViewData["Title"] = "Delete Product";
}

<div class="card">
    <div class="card-body">
        <form asp-action="SureDelete" method="post" id="form_delete">
            <input type="hidden" id="Id" name="Id" value="@Model.Id" />
            <h3>Are you sure for delete @Model.NameProduct ?</h3>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-controller="Product" asp-action="Index" class="btn btn-cyan">No</a>
            </div>
        </form>
    </div>
</div>

<script>
    $("#form_delete").validate({
        submitHandler: function (form) {
            // var dataParam = $(form).serialize()
            var id = $("#Id").val()
            $.ajax({
                url: '/Product/SureDelete',
                type: "post",
                data: { id: id },
                dataType: "json",
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {
                        $("#my_Modal").modal("hide")
                        // toastr.success(
                        //     data.message,
                        //     '',
                        //     {
                        //         timeOut: 500,
                        //         fadeOut: 500,
                        //         onHidden: function () {
                        //             window.location.reload()
                        //         }
                        //     }
                        // )
                        Swal.fire({
                            title: "Information!",
                            text: data.message,
                            icon: "success"
                        }).then((result) => {
                            // Jika pengguna menekan tombol OK, result.value akan berisi true
                            if (result.value) {
                                // Reload halaman setelah menekan tombol OK
                                window.location.reload();
                            }
                        });
                                        }
                    else {
                        toastr.errorClass(data.message)
                    }
                }
            })
        }
    })
</script>

xpos334/xpos334/Views/Product/Detail.cshtml
@using xpos334.viewmodels;
@model VMTblProduct

@{
    Layout = null;
    ViewData["Title"] = "Detail Product";
}

<div class="card">
    <div class="card-body">
        @* <div class="h4 mb-4">@ViewData["Title"]</div> *@
        <div class="card-title">@ViewData["Title"]</div>

 
            <div class="mb-4 row">
                <label for="NameProduct" class="col-sm-4 col-form-label">Name Product</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameProduct" name="NameProduct" value="@Model.NameProduct" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Price" class="col-sm-4 col-form-label">Price</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Price" name="Price" value="@Model.Price" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Stock" class="col-sm-4 col-form-label">Stock</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Stock" name="Stock" value="@Model.Stock" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Image" class="col-sm-4 col-form-label">Upload Image</label>
                <div class="col-sm-8">
                    @if(@Model.Image != null){
                <input type="text" class="form-control" id="Image" name="Image" value="@Model.Image.Split("_")[1]" readonly>
                <img src="~/images/@Model.Image" class="rounded-circle" height="55" width="55" />
                @* <h6>"@Model.Image.Split("_")[1]"</h6> *@
                    }
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-8">
                    <a class="btn btn-light" asp-controller="Product" asp-action="Index">Back to List</a>
                </div>
            </div>

    </div>
</div>

xpos334/xpos334/Views/Product/Edit.cshtml
@using xpos334.viewmodels;
@model VMTblProduct

@{
    Layout = null;
    ViewData["Title"] = "Edit Product";
}

<div class="card">
    <div class="card-body">
        @* <div class="h4 mb-4">@ViewData["Title"]</div> *@
        <div class="card-title">@ViewData["Title"]</div>

        <form asp-action="Edit" method="post" id="form_input" enctype="multipart/form-data">
            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">


            <div class="mb-4 row">
                <label for="NameProduct" class="col-sm-4 col-form-label">Name Product</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameProduct" name="NameProduct" value="@Model.NameProduct">
                    <span id="validate_NameProduct" class="text-danger"></span>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdCategory",
                    new SelectList(ViewBag.ListCategory, "Id", "NameCategory"),
                    "--Pilih Category--",
                    new {@class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdVariant" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdVariant",
                    new SelectList(ViewBag.ListVariant, "Id", "NameVariant"),
                    "--Pilih Variant--",
                    new {@class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Price" class="col-sm-4 col-form-label">Price</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Price" name="Price" value="@Model.Price">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Stock" class="col-sm-4 col-form-label">Stock</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Stock" name="Stock" value="@Model.Stock">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="ImageFile" class="col-sm-4 col-form-label">Upload Image</label>
                <div class="col-sm-8">
                    <input type="file" class="form-control" id="ImageFile" name="ImageFile" value="@Model.Image">
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="Product" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            NameProduct: {
                required: true,
                minlength: 3,
            },
            Price: {
                required: true,
                number: true,
            },
            Stock: {
                required: true,
                number: true,
            },
            IdCategory: "required",
            IdVariant: "required",
            // ImageFile: {
            //     required: true,
            //     typeFile: "jpg|jpeg|png",
            //     sizeFile: true,
            // },
        },
        messages: {
            NameProduct: {
                required: "Please fill Name Product",
                minlength: "The name must consist of at least 3 character"
            },
            Price: {
                required: "Please fill price",
                number: "Please fill number only",
            },
            Stock: {
                required: "Please fill stock",
                number: "Please fill number only",
            },
            IdCategory: "Please select category",
            IdVariant: "Please select category",
            ImageFile: {
                required: "Please fill image",
                typeFile: "Please upload jpn|jpeg|png",
                sizeFile: "Please upload file max size 1 mb",
            },
        },
        submitHandler: function (form) {
            var name = $("#NameProduct").val()
            var id = $("#Id").val()
            var idVariant = $("#IdVariant").val()

            $.ajax({
                url: "/Product/CheckNameIsExist",
                type: "get", //type atau method sama aja.
                data: { name: name, id: id, idVariant: idVariant },
                dataType: "json",
                success: function (respon) {
                    if (respon) {
                        $("#validate_NameProduct").text("Name Product is Already Exists");
                        return true;
                    }
                    else {
                        fungsiSubmit(form)
                    }
                }

            })
        }
    })

    function fungsiSubmit(form) {
        var formData = new FormData()
        var dataForm = $(form).serializeArray()
        $.each(dataForm, function (key, input) {
            formData.append(input.name, input.value)
        })
        var file = $("#ImageFile").prop("files")
        if (file.length > 0) {
            formData.append("ImageFile", file[0])
        }
        $.ajax({
            url: "/Product/Edit",
            type: "post",
            data: formData,
            dataType: "json",
            contentType: false,
            processData: false,
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {
                    $("#my_Modal").modal("hide")

                    // toastr.success(
                    //     data.message,
                    //     '',
                    //     {
                    //         timeOut: 500,
                    //         fadeOut: 500,
                    //         onHidden: function () {
                    //             window.location.reload()
                    //         }
                    //     }

                    // )

                    Swal.fire(
                        'Information',
                        data.message,
                        'success'
                    ).then(function () {
                        window.location.reload();
                    })
                }
                else {
                    Swal.fire({
                        icon: 'error',
                        title: 'warning!',
                        text: data.message
                    })
                }

            }
        })
    }
    jQuery.validator.addMethod("typeFile", function (value, element, param) {
        return value.match(new RegExp("." + param + "$"));
    });
    jQuery.validator.addMethod("sizeFile", function (val, element) {
        var size = element.files[0].size;
        if (size > 1048576)// checks the file more than 1 MB
        {
            return false;
        } else {
            return true;
        }
    });

    $("#IdCategory").change(function () {
        var idCategory = $(this).val()
        $.ajax({
            url: "/Product/GetDataByIdCategory",
            data: { id: idCategory },
            type: "get",
            dataType: "Json",
            success: function (respon) {
                $("#IdVariant").empty()
                $("#IdVariant").append("<option value=''>--PilihVariant--</option>")
                $.each(respon, function (index, res) { //untuk perulangan
                    $("#IdVariant").append("<option value='" + res.id + "'>" + res.nameVariant + "</option>")
                })
            }
        })
    })
</script>