xpos334/xpos334/Controllers/VariantTryController.cs
using Microsoft.AspNetCore.Mvc;
using System.Data;
using xpos334.datamodels;
using xpos334.viewmodels;
using Xpos334.Services;

namespace Xpos334.Controllers
{
    public class VariantTryController : Controller
    {
        private readonly XPOS_334Context db;
        private readonly CategoryTryService categoryService;
        private readonly VariantTryService variantTryService;

        private static VMPage page = new VMPage();

        public VariantTryController(XPOS_334Context _db)
        {
            db = _db;
            categoryService = new CategoryTryService(db);
            variantTryService = new VariantTryService(db);
        }

        public IActionResult Index(VMPage pg)
        {
            ViewBag.idSort = string.IsNullOrEmpty(pg.sortOrder) ? "id_desc" : "";
            ViewBag.nameSort = pg.sortOrder == "name" ? "name_desc" : "name";
            ViewBag.CurrentSort = pg.sortOrder;
            ViewBag.currentShowData = pg.showData;

            if (pg.searchString != null)
            {
                pg.pageNumber = 1;
            }
            else
            {
                pg.searchString = pg.currentFilter;
            }

            ViewBag.CurrentFilter = pg.currentFilter;

            List<VMTblVariant> dataView = variantTryService.GetAllData();

            if (!string.IsNullOrEmpty(pg.searchString))
            {
                dataView = dataView.Where(a => a.NameVariant.ToLower().Contains(pg.searchString.ToLower())
                ).ToList();
            }

            switch (pg.sortOrder)
            {
                case "name_desc":
                    dataView = dataView.OrderByDescending(a => a.NameVariant).ToList();
                    break;
                case "name":
                    dataView = dataView.OrderBy(a => a.NameVariant).ToList();
                    break;
                case "id_desc":
                    dataView = dataView.OrderByDescending(a => a.Id).ToList();
                    break;
                default:
                    dataView = dataView.OrderBy(a => a.Id).ToList();
                    break;

            }

            int pageSize = pg.showData ?? 3;

            page = pg;


            return View(PaginatedList<VMTblVariant>.CreateAsync(dataView, pg.pageNumber ?? 1, pageSize));
        }

        public IActionResult Create()
        {
            VMTblVariant dataView = new VMTblVariant();
            ViewBag.DropdownCategory = categoryService.GetAllData();
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Create(VMTblVariant dataView)
        {
            VMResponse respon = new VMResponse();

            respon = variantTryService.Create(dataView);

            if (respon.Success)
            {
                return RedirectToAction("Index", page);
            }
            ViewBag.DropdownCategory = categoryService.GetAllData();
            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Edit(int id)
        {
            VMTblVariant dataView = variantTryService.GetById(id);
            ViewBag.DropdownCategory = categoryService.GetAllData();
            return View(dataView);
        }

        [HttpPost]
        public IActionResult Edit(VMTblVariant dataView)
        {
            VMResponse respon = new VMResponse();

            respon = variantTryService.Edit(dataView);

            if (respon.Success)
            {
                return RedirectToAction("Index", page);
            }
            ViewBag.DropdownCategory = categoryService.GetAllData();
            respon.Entity = dataView;
            return View(respon.Entity);
        }

        public IActionResult Detail(int id)
        {
            VMTblVariant dataView = variantTryService.GetById(id);
            return View(dataView);
        }

        public IActionResult Delete(int id)
        {
            VMTblVariant dataView = variantTryService.GetById(id);
            return View(dataView);
        }

        [HttpPost]

        public IActionResult Delete(VMTblVariant dataView)
        {
            VMResponse respon = variantTryService.Delete(dataView);
            if (respon.Success)
            {
                return RedirectToAction("Index", page);
            }
            return View(respon.Entity);
        }
    }
}

xpos334/xpos334/Views/VariantTry/Create.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
    ViewData["Title"] = "Create Variant Try";
}

<div class="card">
    <div class="card-body">
        <div class="h4 mb-4">@ViewData["Title"]</div>

        <form asp-action="Create" method="post" id="form_input">
            <div class="mb-4 row">
                <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCategory" name="NameVariant" value="@Model.NameVariant">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdCategory",
                    new SelectList(ViewBag.DropdownCategory, "Id", "NameCategory"),
                    "--Pilih Category--",
                    new {@class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">                 
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="VariantTry" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass:"text-danger",
        rules: {
            NameVariant: {
                required : true,
                minlength : 3,
            },
            IdCategory : "required"
        },
        messages: {
            NameVariant: {
                required : "Please fill Name Variant",
                minlength : "The name must consist of at least 3 characters",
            },
            IdCategory : "Please select category"
        }
    })
</script>

xpos334/xpos334/Views/VariantTry/Delete.cshtml
@using xpos334.viewmodels;
@model VMTblVariant
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    Layout = null;
    ViewData["Title"] = "Delete Variant Try";
}

<div class="card">
    <div class="card-body">
        <form asp-action="Delete" method="post">
            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">
            <div class=" h3 mb-4 row">Are you sure for delete @Model.NameVariant ?</div>
            <div class="mb-4 row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-outline-primary" asp-controller="VariantTry" asp-action="Index">Back To List</a>
                </div>
            </div>
        </form>
    </div>
</div>

xpos334/xpos334/Views/VariantTry/Detail.cshtml
@{
    Layout = null;
    ViewData["Title"] = "Detail Variant Try";
}

<div class="card">
    <div class="card-body">
        <div class="h4 mb-4">@ViewData["Title"]</div>
        @* <input type="text" class="form-control" id="Id" name="Id" value="@Model.Id"> *@
        <form asp-action="Detail" method="post" id="form_input">
            <div class="mb-4 row">
                <label for="NameVariant" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                <input type="text" class="form-control" id="NameCategory" name="NameCategory" value="@Model.NameCategory" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description" readonly>
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="VariantTry" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>

    </div>
</div>

xpos334/xpos334/Views/VariantTry/Edit.cshtml
@{
    Layout = null;
    ViewData["Title"] = "Edit Variant Try";
}

<div class="card">
    <div class="card-body">
        <div class="h4 mb-4">@ViewData["Title"]</div>
        <form asp-action="Edit" method="post" id="form_input">

            <input type="hidden" class="form-control" id="Id" Name="Id" value="@Model.Id">

            <div class="mb-4 row">
                <label for="NameCategory" class="col-sm-4 col-form-label">Name Variant</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameVariant" name="NameVariant" value="@Model.NameVariant">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdCategory" class="col-sm-4 col-form-label">Name Category</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdCategory",
                    new SelectList(ViewBag.DropdownCategory, "Id", "NameCategory"),
                    "--Pilih Category--",
                    new { @class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Description" class="col-sm-4 col-form-label">Description</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Description" name="Description" value="@Model.Description">
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="VariantTry" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>


    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            NameVariant: {
                required: true,
                minlength: 3,
            },
            IdCategory: "required"
        },
        messages: {
            NameVariant: {
                required: "Please fill Name Variant",
                minlength: "The name must consist of at least 3 characters",
            },
            IdCategory: "Please select category"
        }
    })
</script>

xpos334/xpos334/Views/VariantTry/Index.cshtml
@using xpos334.viewmodels;
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
    ViewData["Title"] = "Variant Try";
}

<div class="card">
    <div class="card-body">
        <h1 class="card-title">@ViewData["Title"]</h1>
        <form asp-action="Index" method="get" id="form_search">
        <div class="row mb-3">
            <div class="col-12">
                <div class="d-flex justify-content-between">
                    <button type="button" class="btn btn-primary" id="btn_create">
                        Create
                    </button>
                    <div class="input-group w-50">
                        <input type="text" class="form-control" id="searchString" name="searchString" value="@ViewBag.currentFilter" placeholder="Search.."/>
                    <div class="input-group-prepend">
                        <div class="input-group-text" style="cursor:pointer" id="btn_search"><i class="fas fa-search"></i></div>
                    </div>
                        <div class="input-group-prepend">
                            <div class="input-group-text" style="cursor:pointer" id="btn_reset"><i class="fas fa-redo"></i></div>
                        </div>

                    </div>
                </div>
            </div>

        </div>

        <table class="table table-hover">
            <thead>
                <tr>
                    <th>
                        <a asp-action="Index" asp-route-sortOrder="@ViewBag.idSort"
                           asp-route-currentFilter="@ViewBag.currentFilter"
                           asp-route-pageNumber="@ViewBag.PageIndex"
                           asp-route-showData="@ViewBag.currentshowData">
                            Id
                        </a>
                    </th>
                    <th>
                        <a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort"
                           asp-route-pageNumber="@ViewBag.PageIndex"
                           asp-route-showData="@ViewBag.currentshowData">
                            Name Variant
                        </a>
                    </th>
                    <th>Name Category</th>
                    <th>Description</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @{
                    if (Model.Count > 0)
                        foreach (VMTblVariant item in Model)
                        {
                                            <tr>
                                                <td>@item.Id</td>
                                                <td>@item.NameVariant</td>
                                                <td>@item.NameCategory</td>
                                                <td>@item.Description</td>
                                                <td>
                                                    <a class="btn btn-primary btn_edit" style="color:black" data-id="@item.Id">Edit</a>
                                                    <a class="btn btn-success btn_detail" style="color:black" data-id="@item.Id">Detail</a>
                                                    <a class="btn btn-danger btn_delete" style="color:black" data-id="@item.Id">Delete</a>
                                                </td>
                                            </tr>
                        }
                    else
                    {
                                        <tr>
                                        <td>Data not found</td>
                                        </tr>
                    }
                }
            </tbody>
        </table>
        <div class="row mb-3">
            <div class="col-sm-12">
                <div class="d-flex justify-content-between">
                    <div class="btn-group">
                        <div class="mr-2">
                            show
                        </div>
                        <select name="showData" id="select_show" aria-controls="zero_config" class="form-control form-control-sm w-auto">
                            <option value="3">3</option>
                            <option value="5">5</option>
                            <option value="10">10</option>
                        </select>
                        <div class="ml-2">entries from @Model.TotalData data</div>
                        <input type="hidden" name="sortOrder" id="sort_change" value="" />
                    </div>

                    @{
                        var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
                        var nextDisabled = !Model.HasNextPage ? "disabled" : "";
                    }
                    <div class="w-30">
                        Page @Model.PageIndex of @Model.TotalPages
                        <a asp-action="Index"
                           asp-route-sortOrder="@ViewBag.CurrentSort"
                           asp-route-pageNumber="@(Model.PageIndex - 1)"
                           asp-route-currentFilter="@ViewBag.CurrentFilter"
                           asp-route-showData="@ViewBag.currentShowData"
                           class="btn btn-primary @prevDisabled">
                            Previous
                        </a>
                        <a asp-action="Index"
                           asp-route-sortOrder="@ViewBag.CurrentSort"
                           asp-route-pageNumber="@(Model.PageIndex + 1)"
                           asp-route-currentFilter="@ViewBag.CurrentFilter"
                           asp-route-showData="@ViewBag.currentShowData"
                           class="btn btn-primary @nextDisabled">
                            Next
                        </a>
                    </div>
                </div>
            </div>
        </div>
        </form>
    </div>
</div>

<script>

    $("#btn_create").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("/VariantTry/Create")
        $("#my_Modal").modal("show")
    })

    $(".btn_edit").click(function () {
        var id = $(this).data("id")

        $("#modal_body").empty()
        $("#modal_body").load("/VariantTry/Edit?id=" + id)
        $("#my_Modal").modal("show")
    })

    $(".btn_delete").click(function () {
        var id = $(this).data("id")

        $("#modal_body").empty()
        $("#modal_body").load("/VariantTry/Delete?id=" + id)
        $("#my_Modal").modal("show")
    })

    $(".btn_detail").click(function () {
        var id = $(this).data("id")

        $("#modal_body").empty()
        $("#modal_body").load("/VariantTry/Detail?id=" + id)
        $("#my_Modal").modal("show")
    })

    $("#btn_search").click(function () {
        $("#sort_change").val("@ViewBag.CurrentSort")
        $("#form_search").submit()
    })

    $("#btn_reset").click(function () {
        $("#sort_change").val("")
        $("#form_search").submit()
    })

    $("#select_show").val(@ViewBag.currentShowData)
    $("#select_show").change(function () { 
        $("#sort_change").val("@ViewBag.CurrentSort")
        $("#form_search").submit()
    })
</script>