xpos334/xpos334/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Mvc;
using xpos334.datamodels;
using xpos334.Services;
using xpos334.viewmodels;

namespace xpos334.Controllers
{
    public class CustomerController : Controller
    {
        private RoleService roleService;
        private CustomerService customerService;
        private int IdUser = 1;

        public CustomerController(RoleService _roleService, CustomerService _customerService)
        {
            roleService = _roleService;
            customerService = _customerService;
        }

        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            List<VMTblCustomer> data = await customerService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.NameCustomer.ToLower().Contains(searchString.ToLower())
                    || a.RoleName.ToLower().Contains(searchString.ToLower())).ToList();
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.NameCustomer).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.NameCustomer).ToList();
                    break;
            }

            return View(PaginatedList<VMTblCustomer>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));

        }

        public async Task<IActionResult> Create()
        {

            VMTblCustomer data = new VMTblCustomer();
            List<TblRole> listRole = await roleService.GetAllData();
            ViewBag.ListRole = listRole;

            return PartialView(data);
        }

        public async Task<JsonResult> CheckNameIsExsist(string email, int id)
        {
            bool isExist = await customerService.CheckByName(email, id);
            return Json(isExist);
        }

        [HttpPost]
        public async Task<IActionResult> Create(VMTblCustomer dataParam)
        {
            dataParam.CreateBy = IdUser;
            VMResponse respon = await customerService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }
        public async Task<IActionResult> Edit(int id)
        {

            VMTblCustomer data = await customerService.GetDataById(id);
            List<TblRole> listRole = await roleService.GetAllData();
            ViewBag.ListRole = listRole;

            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(VMTblCustomer dataParam)
        {
            VMResponse respon = await customerService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Detail(int id)
        {
            VMTblCustomer data = await customerService.GetDataById(id);
            return PartialView(data);
        }
        public async Task<IActionResult> Delete(int id)
        {
            VMTblCustomer data = await customerService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            VMResponse respon = await customerService.Delete(id);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return RedirectToAction("Index");
        }
    }
}

xpos334/xpos334/Views/Customer/Create.cshtml
@using xpos334.viewmodels;
@model VMTblCustomer
@{
    ViewData["Title"] = "Create Customer";
}

<div class="card">
    <div class="card-body">
        <div class="h4 mb-4">@ViewData["Title"]</div>

        <form asp-action="Create" method="post" id="form_input">
            <div class="mb-4 row">
                <label for="NameCustomer" class="col-sm-4 col-form-label">Name Customer</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCustomer" name="NameCustomer" value="@Model.NameCustomer">
                </div>
            </div>

            <div class="mb-4 row">
                <label for="IdRole" class="col-sm-4 col-form-label">Name Role</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdRole",
                    new SelectList(ViewBag.ListRole,"Id","RoleName"),
                    "--Select Role--",
                    new{@class = "form-control"}
                    )
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Password" class="col-sm-4 col-form-label">Password</label>
                <div class="col-sm-8">
                    <input type="password" class="form-control" id="Password" name="Password" value="@Model.Password">
                    <input type="checkbox" onclick="showPassword()"/>show password
                </div>
            </div>
            <div class="mb-4 row">
                <label for="Email" class="col-sm-4 col-form-label">Email</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Email" name="Email" value="@Model.Email">
                    <span id="validate_Email" class="text-danger"></span>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Address" class="col-sm-4 col-form-label">Address</label>
                <div class="col-sm-8">
                    <textarea type="text" class="form-control" id="Address" Name="Address">@Model.Address</textarea>
                </div>
            </div>

            <div class="mb-4 row">
                <label for="Phone" class="col-sm-4 col-form-label">Phone</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="Phone" name="Phone" value="@Model.Phone">
                </div>
            </div>

            <div class="mb-4 row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="Customer" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>


    </div>
</div>

<script>

    function showPassword() {
        var x = document.getElementById("Password");
        if (x.type === "password") {
            x.type = "text";
        } else {
            x.type = "password";
        }
    }

    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            Email: {
                required: true,
                minlength: 3,
            },
            IdRole: "required",
            NameCustomer: "required",
            Password: "required",
            Address: "required",
            Phone:"required",
        },
        messages: {
            Email: {
                required: "Please fill Email",
                minlength: "The name must consist of at least 3 characters",
            },
            IdRole: "please select Role",
            NameCustomer: "Please fill Name Customer",
            Password: "Please fill Password",
            Address: "Please fill Address",
            Phone: "Please fill Phone",
        },
        submitHandler: function (form) {

            var dataForm = $(form).serialize()
            var email = $("#Email").val()
            var idRole = $("#IdRole").val()
            var id = 0

            $.ajax({
                url: "/Customer/CheckNameIsExsist",
                type: "get", //type atau method sama aja.
                data: { email: email, idRole: idRole, id: id },
                dataType: "json",
                success: function (respon) {

                    if (respon) {
                        $("#validate_Email").text("Email Already Axists")
                        return true;
                    }
                    else {
                        fungsiSubmit(dataForm)
                    }
                }

            })
        }
    })
    function fungsiSubmit(dataParam) {
        $.ajax({
            url: "/Customer/Create",
            type: "post",
            data: dataParam,
            dataType: "json",
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {
                    $("#my_Modal").modal("hide")

                    toastr.success(
                        data.message,
                        '',
                        {
                            timeOut: 500,
                            fadeOut: 500,
                            onHidden: function () {
                                window.location.reload()
                            }
                        }
                    )
                }
                else {
                    toastr.errorClass(data.message)
                }

            }
        })
    }
</script>

xpos334/xpos334/Views/Customer/Delete.cshtml
@using xpos334.viewmodels;
@model VMTblCustomer
@{
    ViewData["Title"] = "Delete Customer";
}

<div class="card">
    <div class="card-body">
        <form asp-action="SureDelete" method="post" id="form_delete">
            <input type="hidden" id="Id" name="Id" value="@Model.Id" />
            <h3>Are you sure for delete @Model.NameCustomer ?</h3>
            <div class="modal-footer">
                <button type="submit" class="btn btn-primary">Yes</button>
                <a asp-controller="Customer" asp-action="Index" class="btn btn-cyan">No</a>
            </div>
        </form>
    </div>
</div>

<script>
    $("#form_delete").validate({
        submitHandler: function (form) {
            // var dataParam = $(form).serialize()
            var id = $("#Id").val()
            $.ajax({
                url: '/Customer/SureDelete',
                type: "post",
                data: { id: id },
                dataType: "json",
                success: function (respon) {
                    var data = respon.dataRespon
                    if (data.success) {
                        $("#my_Modal").modal("hide")
                        toastr.success(
                            data.message,
                            '',
                            {
                                timeOut: 500,
                                fadeOut: 500,
                                onHidden: function () {
                                    window.location.reload()
                                }
                            }
                        )
                    }
                    else {
                        toastr.errorClass(data.message)
                    }
                }
            })
        }
    })
</script>

xpos334/xpos334/Views/Customer/Detail.cshtml
@using xpos334.viewmodels;
@model VMTblCustomer

@{
    Layout = null;
    ViewData["Title"] = "Detail Customer";
}

<div class="card">
    <div class="card-body">

        @* <div class="h4 mb-4">@ViewData["Title"]</div> *@
        <div class="card-title">@ViewData["Title"]</div>
        <div class="mb-4 row ">
            <label for="NameCustomer" class="col-sm-4 col-form-label">Name Customer</label>
            <div class="col-sm-8">
                <input type="text" class="form-control" id="NameCustomer" Name="NameCustomer" value="@Model.NameCustomer" readonly>
            </div>
        </div>
        <div class="mb-4 row ">
            <label for="IdRole" class="col-sm-4 col-form-label">Name Role</label>
            <div class="col-sm-8">
                <textarea type="text" class="form-control" id="Email" Name="Email" readonly>@Model.IdRole</textarea>
            </div>
        </div>
        <div class="mb-4 row ">
            <label for="Password" class="col-sm-4 col-form-label">Password</label>
            <div class="col-sm-8">
                <textarea type="text" class="form-control" id="Password" Name="Password" readonly>@Model.Password</textarea>
            </div>
        </div>
        <div class="mb-4 row ">
            <label for="Email" class="col-sm-4 col-form-label">Email</label>
            <div class="col-sm-8">
                <textarea type="text" class="form-control" id="Email" Name="Email" readonly>@Model.Email</textarea>
            </div>
        </div>
        <div class="mb-4 row ">
            <label for="Address" class="col-sm-4 col-form-label">Address</label>
            <div class="col-sm-8">
                <textarea type="text" class="form-control" id="Address" Name="Address" readonly>@Model.Address</textarea>
            </div>
        </div>
        <div class="mb-4 row ">
            <label for="Phone" class="col-sm-4 col-form-label">Phone</label>
            <div class="col-sm-8">
                <textarea type="text" class="form-control" id="Phone" Name="Phone" readonly>@Model.Phone</textarea>
            </div>
        </div>

        <div class="mb-4 row">
            <div class="col-sm-8">

                <a class="btn btn-light" asp-controller="Customer" asp-action="Index">Back to List</a>
            </div>
        </div>
    </div>
</div>

xpos334/xpos334/Views/Customer/Edit.cshtml
﻿@using xpos334.viewmodels;
@model VMTblCustomer

@{
    Layout = null;
    ViewData["Title"] = "Edit Customer";
}

<div class="card">
    <div class="card-body">

        @* <div class="h4 mb-4">@ViewData["Title"]</div> *@
        <div class="card-title">@ViewData["Title"]</div>

        <form asp-action="Edit" method="post" id="form_input">
            <input type="hidden" class="form-control" id="Id" name="Id" value="@Model.Id">

            <div class="mb-4 row ">
                <label for="NameCustomer" class="col-sm-4 col-form-label">Name Customer</label>
                <div class="col-sm-8">
                    <input type="text" class="form-control" id="NameCustomer" Name="NameCustomer" value="@Model.NameCustomer">
                </div>
            </div>
            <div class="mb-4 row ">
                <label for="IdRole" class="col-sm-4 col-form-label">Name Role</label>
                <div class="col-sm-8">
                    @Html.DropDownList("IdRole",
                    new SelectList(ViewBag.ListRole, "Id", "RoleName"),
                    "--Pilih Role--",
                    new { @class = "form-control"}
                    )
                </div>
            </div>
            <div class="mb-4 row ">
                <label for="Email" class="col-sm-4 col-form-label">Email</label>
                <div class="col-sm-8">
                    <textarea type="text" class="form-control" id="Email" Name="Email">@Model.Email</textarea>
                    <span id="validate_Email" class="text-danger"></span>

                </div>
            </div>

            <div class="mb-4 row ">
                <label for="Password" class="col-sm-4 col-form-label">Password</label>
                <div class="col-sm-8">
                    <textarea type="text" class="form-control" id="Password" Name="Password">@Model.Password</textarea>
                </div>
            </div>

            <div class="mb-4 row ">
                <label for="Address" class="col-sm-4 col-form-label">Address</label>
                <div class="col-sm-8">
                    <textarea type="text" class="form-control" id="Address" Name="Address">@Model.Address</textarea>
                </div>
            </div>

            <div class="mb-4 row ">
                <label for="Phone" class="col-sm-4 col-form-label">Phone</label>
                <div class="col-sm-8">
                    <textarea type="text" class="form-control" id="Phone" Name="Phone">@Model.Phone</textarea>
                </div>
            </div>

            <div class="form-group row">
                <div class="col-sm-8">
                    <button type="submit" class="btn btn-primary">Submit</button>
                    <a class="btn btn-light" asp-controller="Customer" asp-action="Index">Back to List</a>
                </div>
            </div>
        </form>

    </div>
</div>

<script>
    $("#form_input").validate({
        errorClass: "text-danger",
        rules: {
            Email: {
                required: true,
                minlength: 3,
            },
            Email: "required"
        },
        messages: {
            Email: {
                required: "Please fill Name Customer",
                minlength: "The name must consist of at least 3 characters",
            },
            Email: "please select Role"
        },
        submitHandler: function (form) {

            var dataForm = $(form).serialize()
            var email = $("#Email").val()
            var id = $("#Id").val()

            $.ajax({
                url: "/Customer/CheckNameIsExsist",
                type: "get", //type atau method sama aja.
                data: { email: email, id: id },
                dataType: "json",
                success: function (respon) {

                    if (respon) {
                        $("#validate_Email").text("Email Already Axists")
                        return true;
                    }
                    else {
                        fungsiSubmit(dataForm)
                    }
                }

            })
        }
    })
    function fungsiSubmit(dataParam) {
        $.ajax({
            url: "/Customer/Edit",
            type: "post",
            data: dataParam,
            dataType: "json",
            success: function (respon) {
                var data = respon.dataRespon
                if (data.success) {
                    $("#my_Modal").modal("hide")

                    toastr.success(
                        data.message,
                        '',
                        {
                            timeOut: 500,
                            fadeOut: 500,
                            onHidden: function () {
                                window.location.reload()
                            }
                        }
                    )
                }
                else {
                    toastr.errorClass(data.message)
                }

            }
        })
    }

</script>

xpos334/xpos334/Views/Customer/Index.cshtml
@using xpos334.viewmodels;
@model PaginatedList<VMTblCustomer>

@{
    ViewData["Title"] = "Customer";
}

<div class="card">
    <div class="card-body">

        <h1 class="card-title">@ViewData["Title"]</h1>


        <div class="row mb-3">
            <div class="col-12">
                <div class="d-flex justify-content-between">

                    <button id="btn_create" class="btn btn-primary">Create</button>

                    <form asp-action="Index" asp-route-pageSize="@ViewBag.CurrentPageSize">
                        <div class="input-group w-100">
                            <input type="text" name="searchString" value="@ViewBag.CurrentFilter" class="form-control" placeholder="Search.." />
                            <div class="input-group-prepend">
                                <button type="submit" class="input-group-text" title="search">
                                    <i class="fas fa-search"></i>
                                </button>
                            </div>
                            <div class="input-group-prepend">
                                <a class="input-group-text" asp-action="Index" title="reset">
                                    <i class="fas fa-redo"></i>
                                </a>
                            </div>
                        </div>
                    </form>

                </div>
            </div>
        </div>
        <table class="table table-hover mb-3">
            <thead>
                <tr>
                    <th>
                        <a asp-action="Index" asp-route-sortOrder="@ViewBag.NameSort"
                           asp-route-currentFilter="@ViewBag.currentFilter"
                           asp-route-pageSize="@ViewBag.currentPageSize">
                            Name Customer
                        </a>
                    </th>
                    <th>Role Name</th>
                    <th>Password</th>
                    <th>Email</th>
                    <th>Address</th>
                    <th>Phone</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody>
                @if (Model.Count != 0)
                {
                    @foreach (var item in Model)
                    {
                        <tr>
                            <td>@item.NameCustomer</td>
                            <td>@item.RoleName</td>
                            <td>@item.Password</td>
                            <td>@item.Email</td>
                            <td>@item.Address</td>
                            <td>@item.Phone</td>
                            
                            <td>
                                <a class="btn btn-success btn_edit" style="color:whitesmoke" dataid="@item.Id">Edit</a>
                                <a class="btn btn-warning btn_detail" style="color:whitesmoke" dataid="@item.Id">Detail</a>
                                <a class="btn btn-danger btn_delete" style="color:whitesmoke" dataid="@item.Id">Delete</a>
                            </td>
                        </tr>
                    }
                }
                else
                {
                    <tr>
                        <td>Data not found</td>
                    </tr>
                }


            </tbody>

        </table>
    </div>

    <div class="card-footer">
        @{
            var prevDisabled = !Model.HasPreviousPage ? "disabled" : "";
            var nextDisabled = !Model.HasNextPage ? "disabled" : "";
        }
        <div class="row">
            <div class="col-2">
                <form asp-action="Index" id="form_pagesize">
                    <select name="PageSize" id="PageSize" class="form-control">
                        <option value="3">3</option>
                        <option value="5">5</option>
                        <option value="10">10</option>
                    </select>
                </form>
            </div>
            <div class="col-10">
                Page @Model.PageIndex of @Model.TotalPages
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewBag.CurrentSort"
                   asp-route-pageNumber="@(Model.PageIndex + 1)"
                   asp-route-currentFilter="@ViewBag.CurrentFilter"
                   asp-route-pageSize="@ViewBag.CurrentPageSize"
                   class="btn btn-info float-right @nextDisabled">
                    Next
                </a>
                <a asp-action="Index"
                   asp-route-sortOrder="@ViewBag.CurrentSort"
                   asp-route-pageNumber="@(Model.PageIndex - 1)"
                   asp-route-currentFilter="@ViewBag.CurrentFilter"
                   asp-route-pageSize="@ViewBag.CurrentPageSize"
                   class="btn btn-info float-right @prevDisabled">
                    Previous
                </a>
            </div>
        </div>


    </div>
</div>


<script>

    $("#btn_create").click(function () {
        $("#modal_body").empty()
        $("#modal_body").load("/Customer/Create")
        $("#my_Modal").modal("show")
    })

    $(".btn_edit").click(function () {
        var id = $(this).attr("dataid")

        $("#modal_body").empty()
        $("#modal_body").load("/Customer/Edit?id=" + id)
        $("#my_Modal").modal("show")
    })

    $(".btn_detail").click(function () {
        var id = $(this).attr("dataid")

        $("#modal_body").empty()
        $("#modal_body").load("/Customer/Detail?id=" + id)
        $("#my_Modal").modal("show")
    })

    $(".btn_delete").click(function () {
        var id = $(this).attr("dataid")

        $("#modal_body").empty()
        $("#modal_body").load("/Customer/Delete?id=" + id)
        $("#my_Modal").modal("show")
    })



    $("#PageSize").val(@ViewBag.CurrentPageSize)

    $("#PageSize").change(function () {
        $("#form_pagesize").submit()
    })
</script>