xpos334/xpos334/Controllers/AuthController.cs
using Microsoft.AspNetCore.Mvc;
using xpos334.datamodels;
using xpos334.Services;
using xpos334.viewmodels;
using Xpos334.Services;

namespace Xpos334.Controllers
{
    public class AuthController : Controller
    {
        private AuthService authService;
        private RoleService roleService;
        VMResponse respon = new VMResponse();

        public AuthController(AuthService _authService, RoleService _roleService)
        {
            authService = _authService;
            roleService = _roleService;
        }

        public IActionResult Login()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<JsonResult> LoginSubmit(string email, string password)
        {
            VMTblCustomer customer = await authService.CheckLogin(email, password);

            if (customer != null)
            {
                respon.Message = $"Hello, {customer.NameCustomer} Welcome to XPOS";
                HttpContext.Session.SetString("NameCustomer", customer.NameCustomer);
                HttpContext.Session.SetInt32("IdCustomer", customer.Id);
                HttpContext.Session.SetInt32("IdRole", customer.IdRole ?? 0);
            }
            else
            {
                respon.Success = false;
                respon.Message = $"Oops, {email} not found or password is wrong, please check again";
            }
            return Json(new { dataRespon = respon });
        }

        public IActionResult Logout()
        {
            HttpContext.Session.Clear();
            return RedirectToAction("Index", "Home");
        }
        public async Task<IActionResult> Register()
        {

            VMTblCustomer data = new VMTblCustomer();
            List<TblRole> listRole = await roleService.GetAllData();
            ViewBag.ListRole = listRole;

            return PartialView(data);
        }

    }
}

xpos334/xpos334/Controllers/FriendController.cs
using Microsoft.AspNetCore.Mvc;
using xpos334.Models;

namespace xpos334.Controllers
{
    public class FriendController : Controller
    {
       private static List<Friend> friends = new List<Friend>()
            {
                new Friend(){Id = 1, Name = "Irvan", Address = "Kemayoran"},
                new Friend(){Id = 2, Name = "Tunggul", Address = "Cilandak"},
                new Friend(){Id = 3, Name = "Sabrina", Address = "Radio Dalam"}
            };

        public IActionResult Index()
        {
            /*List<Friend> friends = new List<Friend>()
            {
                new Friend(){Id = 1, Name = "Irvan", Address = "Kemayoran"},
                new Friend(){Id = 2, Name = "Tunggul", Address = "Cilandak"},
                new Friend(){Id = 3, Name = "Sabrina", Address = "Radio Dalam"}
            };*/
            ViewBag.listFriend = friends;
            return View(friends);
        }

        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        public IActionResult Create(Friend friend)
        {
            friends.Add(friend);

            return RedirectToAction("Index");
        }
        public IActionResult Edit(int id) 
        {
            //Friend friend = friends[id];
            Friend friend = friends.Find(a => a.Id == id)!;
            return View(friend);
        }
        [HttpPost]
        public IActionResult Edit(Friend data)
        {
            Friend friend = friends.Find(a => a.Id == data.Id);
            int index = friends.IndexOf(friend);
            if (index >-1)
            {
                friends[index].Name = data.Name;
                friends[index].Address = data.Address;
            }
            return RedirectToAction("Index");
        }
        public IActionResult Detail(int id)
        {
            //Friend friend = friends[id];
            Friend friend = friends.Find(a => a.Id == id)!;
            return View(friend);
        }

        public IActionResult Delete(int id)
        {
            //Friend friend = friends[id];
            Friend friend = friends.Find(a => a.Id == id)!;
            return View(friend);
        }

        [HttpPost]
        
        public IActionResult Delete(Friend data) 
        {
            Friend friend = friends.Find(a => a.Id == data.Id);
            friends.Remove(friend);
            return RedirectToAction("Index");
        }
    }
}

xpos334/xpos334/Controllers/OrderController.cs
using Microsoft.AspNetCore.Mvc;
using Newtonsoft.Json;
using NuGet.Configuration;
using xpos334.Services;
using xpos334.viewmodels;
using Xpos334.Services;

namespace Xpos334.Controllers
{
    public class OrderController : Controller
    {
        private ProductService productService;
        private OrderService orderService;
        private int IdUser = 1;

        public OrderController(ProductService _productService, OrderService _orderService) // activate service di constructor
        {
            productService = _productService;
            orderService = _orderService;
        }

        public async Task<IActionResult> Catalog(VMSearchPage dataSearch)
        {
            List<VMTblProduct> dataProduct = await productService.GetAllData();
            dataSearch.MinAmount = dataSearch.MinAmount == null ? decimal.MinValue : dataSearch.MinAmount;
            dataSearch.MaxAmount = dataSearch.MaxAmount == null ? decimal.MaxValue : dataSearch.MaxAmount;
            //dataSearch.MaxAmount = dataSearch.MaxAmount ?? decimal.MaxValue;//jika null data decimal jika tidak maka data searchnya sendiri

            if (dataSearch.NameProduct != null)
            {
                dataProduct = dataProduct.Where(a => a.NameProduct.ToLower().Contains(dataSearch.NameProduct.ToLower())).ToList();
            }
            if (dataSearch.MinAmount != null && dataSearch.MaxAmount != null)
            {
                dataProduct = dataProduct.Where(a => a.Price >= dataSearch.MinAmount
                              && a.Price <= dataSearch.MaxAmount).ToList();
            }

            //Get session in VMOrderHeader first load
            VMOrderHeader dataHeader = HttpContext.Session.GetComplexData<VMOrderHeader>("ListCart");
            if (dataHeader == null)
            {
                dataHeader = new VMOrderHeader();
                dataHeader.ListDetails = new List<VMOrderDetail>();
            }

            var ListDetail = JsonConvert.SerializeObject(dataHeader.ListDetails);
            ViewBag.dataHeader = dataHeader;
            ViewBag.dataDetail = ListDetail;

            ViewBag.Search = dataSearch;
            ViewBag.CurrentPageSize = dataSearch.pageSize;

            return View(PaginatedList<VMTblProduct>.CreateAsync(dataProduct, dataSearch.pageNumber ?? 1, dataSearch.pageSize ?? 3));
        }

        //set session in VMOrderHeader every add or minus
        [HttpPost]
        public JsonResult SetSession(VMOrderHeader dataHeader)
        {
            HttpContext.Session.SetComplexData("ListCart", dataHeader);
            return Json("");
        }

        //remove session
        public JsonResult RemoveSession()
        {
            HttpContext.Session.Remove("ListCart");
            //HttpContext.Session.Clear(); //Clear all session
            return Json("");
        }

        public IActionResult OrderPreview(VMOrderHeader dataHeader)
        {
            return PartialView(dataHeader);
        }

        public IActionResult SearchMenu()
        {
            return PartialView();
        }

        [HttpPost]
        public async Task<JsonResult> SubmitOrder(VMOrderHeader dataHeader)
        {
            //dataHeader.IdCustomer = HttpContext.Session.GetInt32("IdCustomer") ?? 0;
            dataHeader.IdCustomer = IdUser;
            //dataHeader.CodeTransaction = dataHeader.CodeTransaction ?? ""; //cara 1, cara 2 menambahkan tanda tanya pada data yang tidak boleh null yaitu di viewmodels

            VMResponse respon = await orderService.SubmitOrder(dataHeader);
            return Json(respon);
        }

        public async Task<IActionResult> HistoryOrder(VMSearchPage dataSearch)
        {
            //int IdCustomer = HttpContext.Session.GetInt32("IdCustomer") ?? 0;
            int IdCustomer = IdUser;
            List<VMOrderHeader> data = await orderService.GetDataOrderHeaderDetail(IdCustomer);
            int count = await orderService.CountTransaction(IdCustomer);
            ViewBag.Count = count;
            dataSearch.MinDate = dataSearch.MinDate == null ? DateTime.MinValue : dataSearch.MinDate;
            dataSearch.MaxDate = dataSearch.MaxDate == null ? DateTime.MaxValue : dataSearch.MaxDate;

            dataSearch.MinAmount = dataSearch.MinAmount == null ? decimal.MinValue : dataSearch.MinAmount;
            dataSearch.MaxAmount = dataSearch.MaxAmount == null ? decimal.MaxValue : dataSearch.MaxAmount;

            if (!string.IsNullOrEmpty(dataSearch.CodeTransaction))
            {
                data = data.Where(a => a.CodeTransaction.ToLower().Contains(dataSearch.CodeTransaction.ToLower())).ToList();
            }
            if(dataSearch.MinDate != null && dataSearch.MaxDate != null)
            {
                data = data.Where(a => a.CreateDate.Date >= dataSearch.MinDate && a.CreateDate.Date <= dataSearch.MaxDate).ToList();
            }
            if (dataSearch.MinAmount != null && dataSearch.MaxAmount != null)
            {
                data = data.Where(a => a.Amount >= dataSearch.MinAmount && a.Amount <= dataSearch.MaxAmount).ToList();
            }
            ViewBag.Search = dataSearch;

            return View(data);
        }
        public IActionResult Search()
        {
            return PartialView();
        }
        //public IActionResult GeneratePDF(VMOrderHeader dataHeader)
        //{
        //    // Logika untuk pembuatan file PDF atau penyediaan data
        //    // ...

        //    // Contoh: Mengembalikan hasil dalam format PDF
        //    var pdfBytes = GetPDFBytes(); // Fungsi untuk mendapatkan byte PDF

        //    // Menyertakan file PDF sebagai respons
        //    return File(pdfBytes, "application/pdf", "OrderPreview.pdf");
        //}

    }
}

xpos334/xpos334/Controllers/RoleController.cs
using Microsoft.AspNetCore.Mvc;
using xpos334.datamodels;
using xpos334.Services;
using xpos334.viewmodels;
using Xpos334.Services;

namespace xpos334.Controllers
{
    public class RoleController : Controller
    {
        private RoleService roleService;
        private int IdUser = 1;

        public RoleController(RoleService _roleService)
        {
            roleService = _roleService;
        }
        public async Task<IActionResult> Index(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            List<TblRole> data = await roleService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.RoleName.ToLower().Contains(searchString.ToLower())).ToList();
                   
            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.RoleName).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.RoleName).ToList();
                    break;
            }

            return View(PaginatedList<TblRole>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }
        public async Task<IActionResult> Index_MenuAccess(string sortOrder, string searchString, string currentFilter, int? pageNumber, int? pageSize)
        {
            ViewBag.CurrentSort = sortOrder;
            ViewBag.CurrentPageSize = pageSize;
            ViewBag.NameSort = string.IsNullOrEmpty(sortOrder) ? "name_desc" : "";

            if (searchString != null)
            {
                pageNumber = 1;
            }
            else
            {
                searchString = currentFilter;
            }
            ViewBag.CurrentFilter = searchString;

            List<TblRole> data = await roleService.GetAllData();

            if (!string.IsNullOrEmpty(searchString))
            {
                data = data.Where(a => a.RoleName.ToLower().Contains(searchString.ToLower())).ToList();

            }

            switch (sortOrder)
            {
                case "name_desc":
                    data = data.OrderByDescending(a => a.RoleName).ToList();
                    break;
                default:
                    data = data.OrderBy(a => a.RoleName).ToList();
                    break;
            }

            return View(PaginatedList<TblRole>.CreateAsync(data, pageNumber ?? 1, pageSize ?? 3));
        }
        public IActionResult Create()
        {
            TblRole data = new TblRole();
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> Create(TblRole dataParam)
        {
            dataParam.CreatedBy = IdUser;
            VMResponse respon = await roleService.Create(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return View(dataParam);
        }

        public async Task<JsonResult> CheckNameIsExist(string roleName, int id)
        {
            bool isExist = await roleService.CheckNameRoleByName(roleName, id);
            return Json(isExist);
        }

        public async Task<IActionResult> Edit(int id)
        {
            TblRole data = await roleService.GetDataById(id);
            return PartialView(data);
        }
        public async Task<IActionResult> Edit_MenuAccess(int id)
        {
            VMTblRole data = await roleService.GetDataById_MenuAccess(id);
            ViewBag.role_menu = data.role_menu;
            return PartialView(data);
        }


        [HttpPost]
        public async Task<IActionResult> Edit(TblRole dataParam)
        {
            dataParam.UpdatedBy = IdUser;
            VMResponse respon = await roleService.Edit(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        [HttpPost]
        public async Task<IActionResult> Edit_MenuAccess(VMTblRole dataParam)
        {
            dataParam.UpdatedBy = IdUser;
            VMResponse respon = await roleService.Edit_MenuAccess(dataParam);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }

            return View(dataParam);
        }

        public async Task<IActionResult> Detail(int id)
        {
            TblRole data = await roleService.GetDataById(id);
            return PartialView(data);
        }

        public async Task<IActionResult> Delete(int id)
        {
            TblRole data = await roleService.GetDataById(id);
            return PartialView(data);
        }

        [HttpPost]
        public async Task<IActionResult> SureDelete(int id)
        {
            int createdBy = IdUser;
            VMResponse respon = await roleService.Delete(id, createdBy);

            if (respon.Success)
            {
                return Json(new { dataRespon = respon });
            }
            return RedirectToAction("Index");
        }
       
    }
}

xpos334/xpos334/Views/Shared/_Layout_Old.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - xpos334</title>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/xpos334.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">xpos334</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Friend" asp-action="Index">Friend</a>
                        </li> 
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="CategoryTry" asp-action="Index">CategoryTry</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - xpos334 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <!-- Modal -->
    <div class="modal fade" id="my_Modal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h5 class="modal-title" id="exampleModalLabel">Modal title</h5>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body" id="modal_body">
                    ...
                </div>
          @*       <div class="modal-footer">
                    <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                    <button type="button" class="btn btn-primary">Save changes</button>
                </div>
           *@  </div>
        </div>
    </div>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

xpos334/xpos334/Views/Shared/_Sidebar.cshtml
@using Xpos334.Services;
@using xpos334.Services;
@inject AuthService authService

@{
    int IdCustomer = @Context.Session.GetInt32("IdCustomer") ?? 0;
    // string NameCustomer = @Context.Session.GetString("NameCustomer") ?? "";
    int IdRole = @Context.Session.GetInt32("IdRole") ?? 0;
    var menus = await authService.MenuAccess(IdRole);
}

<!-- ============================================================== -->
<!-- Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->
<aside class="left-sidebar" data-sidebarbg="skin6">
@*     @{
        if (IdCustomer != 0)
        {
    <!-- Sidebar scroll-->
    <div class="scroll-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">
                <li class="sidebar-item">
                        <a class="sidebar-link sidebar-link" asp-controller="Home" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="home" class="feather-icon" style="color:brown"></i> 
                        <span class="hide-menu">Dashboard</span>
                    </a>
                </li>
                <li class="list-divider"></li>
                <li class="nav-small-cap"><span class="hide-menu">Master</span></li>

                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="Friend" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="users" class="feather-icon" style="color:blue"></i>
                        <span class="hide-menu">Friend
                        </span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="CategoryTry" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="message-square" class="feather-icon" style="color:green"></i>
                        <span class="hide-menu">Category Try
                        </span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="VariantTry" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="instagram" class="feather-icon" style="color:red"></i><span class="hide-menu">
                            Variant Try
                        </span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Category" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="anchor" class="feather-icon" style="color:darkorange"></i><span class="hide-menu">
                            Category
                        </span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Variant" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="slack" class="feather-icon" style="color:brown"></i><span class="hide-menu">
                            Variant
                        </span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Product" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="inbox" class="feather-icon" style="color:darkorchid"></i><span class="hide-menu">
                            Product
                        </span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Role" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="anchor" class="feather-icon" style="color:darkorange"></i><span class="hide-menu">
                            Role
                        </span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Customer" asp-action="Index"
                       aria-expanded="false">
                        <i data-feather="slack" class="feather-icon" style="color:brown"></i><span class="hide-menu">
                            Customer
                        </span>
                    </a>
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Role" asp-action="Index_MenuAccess"
                       aria-expanded="false">
                        <i data-feather="anchor" class="feather-icon" style="color:darkorange"></i><span class="hide-menu">
                            Atur Menu Access
                        </span>
                    </a>
                </li>

                <li class="list-divider"></li>
                <li class="nav-small-cap"><span class="hide-menu">Transaction</span></li>

                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="Order" asp-action="Catalog"
                       aria-expanded="false">
                        <i data-feather="shopping-cart" class="feather-icon" style="color:darkolivegreen"></i>
                        <span class="hide-menu">
                            Catalog
                        </span>
                    </a>
                </li>

                <li class="sidebar-item">
                    <a class="sidebar-link" asp-controller="Order" asp-action="HistoryOrder"
                       aria-expanded="false">
                        <i data-feather="shopping-bag" class="feather-icon" style="color:coral"></i>
                        <span class="hide-menu">
                            History Order
                        </span>
                    </a>
                </li>

                        <li class="list-divider"></li>
               
                <li class="sidebar-item">
                   
                </li>
                <li class="sidebar-item">
                    <a class="sidebar-link sidebar-link" asp-controller="Auth" asp-action="Logout"
                       aria-expanded="false">
                        <i data-feather="log-out" class="feather-icon"></i><span class="hide-menu">Logout</span>
                    </a>
                </li>
            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->
    }
    } *@

    <!-- Sidebar scroll-->
    <div class="scroll-sidebar" data-sidebarbg="skin6">
        <!-- Sidebar navigation-->
        <nav class="sidebar-nav">
            <ul id="sidebarnav">

                @foreach (var parent in menus)
                {
                    <li class="sidebar-item">
                        <a class="sidebar-link has-arrow" href="javascript:void(0)"
                           aria-expanded="false">
                            <i data-feather="@parent.MenuIcon" class="feather-icon"></i>
                            <span class="hide-menu">@parent.MenuName</span>
                        </a>
                        <ul aria-expanded="false" class="collapse first-level base-level-line">

                            @foreach (var child in parent.ListChild)
                            {
                                <li class="sidebar-item">
                                    <a asp-controller="@child.MenuController" asp-action="@child.MenuAction" class="sidebar-link">
                                        <span class="hide-menu">@child.MenuName</span>
                                    </a>
                                </li>
                            }

                        </ul>
                    </li>
                }

            </ul>
        </nav>
        <!-- End Sidebar navigation -->
    </div>
    <!-- End Sidebar scroll-->



</aside>
<!-- ============================================================== -->
<!-- End Left Sidebar - style you can find in sidebar.scss  -->
<!-- ============================================================== -->